<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <id>https://azu.github.io/github-advisory-database-rss/pip.rss</id>
    <title>Security Advisory for Python packages hosted at PyPI.org</title>
    <updated>2024-10-26T13:04:36.085Z</updated>
    <generator>github-advisory-database-rss</generator>
    <link rel="alternate" href="https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"/>
    <subtitle>Security Advisory for Python packages hosted at PyPI.org on GitHub</subtitle>
    <rights>github-advisory-database-rss</rights>
    <category term="CRITICAL"/>
    <category term="HIGH"/>
    <category term="MODERATE"/>
    <category term="LOW"/>
    <entry>
        <title type="html"><![CDATA[[redis] redis-py Race Condition due to incomplete fix]]></title>
        <id>https://github.com/advisories/GHSA-8fww-64cx-x8p5</id>
        <link href="https://github.com/advisories/GHSA-8fww-64cx-x8p5"/>
        <updated>2024-10-25T21:45:10.000Z</updated>
        <content type="html"><![CDATA[<p>redis-py through 4.5.3 and 4.4.3 leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a non-pipeline operation), and can send response data to the client of an unrelated request. NOTE: this issue exists because of an incomplete fix for CVE-2023-28858.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2023-28859">https://nvd.nist.gov/vuln/detail/CVE-2023-28859</a></li>
<li><a href="https://github.com/redis/redis-py/issues/2665">https://github.com/redis/redis-py/issues/2665</a></li>
<li><a href="https://github.com/redis/redis-py/pull/2641">https://github.com/redis/redis-py/pull/2641</a></li>
<li><a href="https://github.com/redis/redis-py/pull/2666">https://github.com/redis/redis-py/pull/2666</a></li>
<li><a href="https://github.com/redis/redis-py/pull/2671">https://github.com/redis/redis-py/pull/2671</a></li>
<li><a href="https://github.com/redis/redis-py/releases/tag/v4.4.4">https://github.com/redis/redis-py/releases/tag/v4.4.4</a></li>
<li><a href="https://github.com/redis/redis-py/releases/tag/v4.5.4">https://github.com/redis/redis-py/releases/tag/v4.5.4</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml</a></li>
<li><a href="https://github.com/redis/redis-py/pull/1899">https://github.com/redis/redis-py/pull/1899</a></li>
<li><a href="https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965">https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965</a></li>
<li><a href="https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb">https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb</a></li>
<li><a href="https://github.com/advisories/GHSA-8fww-64cx-x8p5">https://github.com/advisories/GHSA-8fww-64cx-x8p5</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-8fww-64cx-x8p5</uri>
        </author>
        <category label="severity" term="HIGH"/>
        <published>2023-03-26T21:30:23.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[redis] redis-py Race Condition due to incomplete fix]]></title>
        <id>https://github.com/advisories/GHSA-8fww-64cx-x8p5</id>
        <link href="https://github.com/advisories/GHSA-8fww-64cx-x8p5"/>
        <updated>2024-10-25T21:45:10.000Z</updated>
        <content type="html"><![CDATA[<p>redis-py through 4.5.3 and 4.4.3 leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a non-pipeline operation), and can send response data to the client of an unrelated request. NOTE: this issue exists because of an incomplete fix for CVE-2023-28858.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2023-28859">https://nvd.nist.gov/vuln/detail/CVE-2023-28859</a></li>
<li><a href="https://github.com/redis/redis-py/issues/2665">https://github.com/redis/redis-py/issues/2665</a></li>
<li><a href="https://github.com/redis/redis-py/pull/2641">https://github.com/redis/redis-py/pull/2641</a></li>
<li><a href="https://github.com/redis/redis-py/pull/2666">https://github.com/redis/redis-py/pull/2666</a></li>
<li><a href="https://github.com/redis/redis-py/pull/2671">https://github.com/redis/redis-py/pull/2671</a></li>
<li><a href="https://github.com/redis/redis-py/releases/tag/v4.4.4">https://github.com/redis/redis-py/releases/tag/v4.4.4</a></li>
<li><a href="https://github.com/redis/redis-py/releases/tag/v4.5.4">https://github.com/redis/redis-py/releases/tag/v4.5.4</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml</a></li>
<li><a href="https://github.com/redis/redis-py/pull/1899">https://github.com/redis/redis-py/pull/1899</a></li>
<li><a href="https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965">https://github.com/redis/redis-py/commit/66a4d6b2a493dd3a20cc299ab5fef3c14baad965</a></li>
<li><a href="https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb">https://github.com/redis/redis-py/commit/b3c89acd0ffe8303649ad8207bc911b1d6a033eb</a></li>
<li><a href="https://github.com/advisories/GHSA-8fww-64cx-x8p5">https://github.com/advisories/GHSA-8fww-64cx-x8p5</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-8fww-64cx-x8p5</uri>
        </author>
        <category label="severity" term="HIGH"/>
        <published>2023-03-26T21:30:23.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[qutebrowser] Qutebrowser XSS Vulnerability]]></title>
        <id>https://github.com/advisories/GHSA-m4fw-77v7-924m</id>
        <link href="https://github.com/advisories/GHSA-m4fw-77v7-924m"/>
        <updated>2024-10-25T21:36:49.000Z</updated>
        <content type="html"><![CDATA[<p>qutebrowser version introduced in v0.11.0 (<a href="https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f">1179ee7a937fb31414d77d9970bac21095358449</a>) contains a Cross Site Scripting (XSS) vulnerability in history command, <code>qute://history</code> page that can result in Via injected JavaScript code, a website can steal the user's browsing history. This attack appear to be exploitable via the victim must open a page with a specially crafted <code>&lt;title&gt;</code> attribute, and then open the <code>qute://history</code> site via the <code>:history</code> command. This vulnerability appears to have been fixed in fixed in v1.3.3 (<a href="https://github.com/qutebrowser/qutebrowser/commit/4c9360237f186681b1e3f2a0f30c45161cf405c7">4c9360237f186681b1e3f2a0f30c45161cf405c7</a>, to be released today) and v1.4.0 (<a href="https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f">5a7869f2feaa346853d2a85413d6527c87ef0d9f</a>, released later this week).</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2018-1000559">https://nvd.nist.gov/vuln/detail/CVE-2018-1000559</a></li>
<li><a href="https://github.com/qutebrowser/qutebrowser/issues/4011">https://github.com/qutebrowser/qutebrowser/issues/4011</a></li>
<li><a href="https://github.com/qutebrowser/qutebrowser/commit/4c9360237f186681b1e3f2a0f30c45161cf405c7">https://github.com/qutebrowser/qutebrowser/commit/4c9360237f186681b1e3f2a0f30c45161cf405c7</a></li>
<li><a href="https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f">https://github.com/qutebrowser/qutebrowser/commit/5a7869f2feaa346853d2a85413d6527c87ef0d9f</a></li>
<li><a href="https://github.com/advisories/GHSA-m4fw-77v7-924m">https://github.com/advisories/GHSA-m4fw-77v7-924m</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/qutebrowser/PYSEC-2018-26.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/qutebrowser/PYSEC-2018-26.yaml</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-m4fw-77v7-924m</uri>
        </author>
        <category label="severity" term="MODERATE"/>
        <published>2018-09-13T15:47:57.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[pyyaml] Improper Input Validation in PyYAML]]></title>
        <id>https://github.com/advisories/GHSA-6757-jp84-gxfx</id>
        <link href="https://github.com/advisories/GHSA-6757-jp84-gxfx"/>
        <updated>2024-10-25T21:35:11.000Z</updated>
        <content type="html"><![CDATA[<p>A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2020-1747">https://nvd.nist.gov/vuln/detail/CVE-2020-1747</a></li>
<li><a href="https://github.com/yaml/pyyaml/pull/386">https://github.com/yaml/pyyaml/pull/386</a></li>
<li><a href="https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747</a></li>
<li><a href="http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html">http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html</a></li>
<li><a href="http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html">http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html</a></li>
<li><a href="https://www.oracle.com/security-alerts/cpujul2022.html">https://www.oracle.com/security-alerts/cpujul2022.html</a></li>
<li><a href="https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0">https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0</a></li>
<li><a href="https://github.com/advisories/GHSA-6757-jp84-gxfx">https://github.com/advisories/GHSA-6757-jp84-gxfx</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2020-96.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2020-96.yaml</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-6757-jp84-gxfx</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2021-04-20T16:14:24.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[PyYAML] Improper Input Validation in PyYAML]]></title>
        <id>https://github.com/advisories/GHSA-8q59-q68h-6hv4</id>
        <link href="https://github.com/advisories/GHSA-8q59-q68h-6hv4"/>
        <updated>2024-10-25T21:31:46.000Z</updated>
        <content type="html"><![CDATA[<p>A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2020-14343">https://nvd.nist.gov/vuln/detail/CVE-2020-14343</a></li>
<li><a href="https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc">https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc</a></li>
<li><a href="https://bugzilla.redhat.com/show_bug.cgi?id=1860466">https://bugzilla.redhat.com/show_bug.cgi?id=1860466</a></li>
<li><a href="https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966">https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966</a></li>
<li><a href="https://www.oracle.com/security-alerts/cpuapr2022.html">https://www.oracle.com/security-alerts/cpuapr2022.html</a></li>
<li><a href="https://www.oracle.com/security-alerts/cpujul2022.html">https://www.oracle.com/security-alerts/cpujul2022.html</a></li>
<li><a href="https://github.com/SeldonIO/seldon-core/issues/2252">https://github.com/SeldonIO/seldon-core/issues/2252</a></li>
<li><a href="https://github.com/yaml/pyyaml/issues/420">https://github.com/yaml/pyyaml/issues/420</a></li>
<li><a href="https://github.com/advisories/GHSA-8q59-q68h-6hv4">https://github.com/advisories/GHSA-8q59-q68h-6hv4</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2021-142.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2021-142.yaml</a></li>
<li><a href="https://pypi.org/project/PyYAML">https://pypi.org/project/PyYAML</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-8q59-q68h-6hv4</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2021-03-25T21:26:26.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[python-keystoneclient] Inadequate Encryption Strength in python-keystoneclient]]></title>
        <id>https://github.com/advisories/GHSA-c3xq-cj8f-7829</id>
        <link href="https://github.com/advisories/GHSA-c3xq-cj8f-7829"/>
        <updated>2024-10-25T21:26:24.000Z</updated>
        <content type="html"><![CDATA[<p>python-keystoneclient version 0.2.3 to 0.2.5 has middleware memcache encryption bypass.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2013-2166">https://nvd.nist.gov/vuln/detail/CVE-2013-2166</a></li>
<li><a href="https://github.com/openstack/python-keystoneclient/commit/eeefb784f24c37d5f56a421e1ccc911cace9385e">https://github.com/openstack/python-keystoneclient/commit/eeefb784f24c37d5f56a421e1ccc911cace9385e</a></li>
<li><a href="https://access.redhat.com/security/cve/cve-2013-2166">https://access.redhat.com/security/cve/cve-2013-2166</a></li>
<li><a href="https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2166">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2166</a></li>
<li><a href="https://bugzilla.suse.com/show_bug.cgi?id=CVE-2013-2166">https://bugzilla.suse.com/show_bug.cgi?id=CVE-2013-2166</a></li>
<li><a href="https://security-tracker.debian.org/tracker/CVE-2013-2166">https://security-tracker.debian.org/tracker/CVE-2013-2166</a></li>
<li><a href="http://lists.fedoraproject.org/pipermail/package-announce/2013-August/113944.html">http://lists.fedoraproject.org/pipermail/package-announce/2013-August/113944.html</a></li>
<li><a href="http://rhn.redhat.com/errata/RHSA-2013-0992.html">http://rhn.redhat.com/errata/RHSA-2013-0992.html</a></li>
<li><a href="http://www.openwall.com/lists/oss-security/2013/06/19/5">http://www.openwall.com/lists/oss-security/2013/06/19/5</a></li>
<li><a href="https://github.com/advisories/GHSA-c3xq-cj8f-7829">https://github.com/advisories/GHSA-c3xq-cj8f-7829</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/python-keystoneclient/PYSEC-2019-197.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/python-keystoneclient/PYSEC-2019-197.yaml</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-c3xq-cj8f-7829</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2021-10-12T16:31:43.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[python-swiftclient] Python Swift client is vulnerable to Missing SSL Certificate Check]]></title>
        <id>https://github.com/advisories/GHSA-p3xv-97g8-4wmj</id>
        <link href="https://github.com/advisories/GHSA-p3xv-97g8-4wmj"/>
        <updated>2024-10-25T21:25:11.000Z</updated>
        <content type="html"><![CDATA[<p>The OpenStack Python client library for Swift (python-swiftclient) from 1.0 before 2.0.2 does not verify X.509 certificates from SSL servers, which allows man-in-the-middle attackers to spoof servers and obtain sensitive information via a crafted certificate.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2013-6396">https://nvd.nist.gov/vuln/detail/CVE-2013-6396</a></li>
<li><a href="https://bugs.launchpad.net/python-swiftclient/+bug/1199783">https://bugs.launchpad.net/python-swiftclient/+bug/1199783</a></li>
<li><a href="http://www.openwall.com/lists/oss-security/2014/02/17/7">http://www.openwall.com/lists/oss-security/2014/02/17/7</a></li>
<li><a href="https://review.opendev.org/c/openstack/python-swiftclient/+/69187">https://review.opendev.org/c/openstack/python-swiftclient/+/69187</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/python-swiftclient/PYSEC-2014-12.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/python-swiftclient/PYSEC-2014-12.yaml</a></li>
<li><a href="https://github.com/advisories/GHSA-p3xv-97g8-4wmj">https://github.com/advisories/GHSA-p3xv-97g8-4wmj</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-p3xv-97g8-4wmj</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2022-05-17T04:52:37.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[pytorch-lightning] Code Injection in PyTorch Lightning]]></title>
        <id>https://github.com/advisories/GHSA-r5qj-cvf9-p85h</id>
        <link href="https://github.com/advisories/GHSA-r5qj-cvf9-p85h"/>
        <updated>2024-10-25T20:49:59.000Z</updated>
        <content type="html"><![CDATA[<p>PyTorch Lightning version 1.5.10 and prior is vulnerable to code injection. An attacker could execute commands on the target OS running the operating system by setting the <code>PL_TRAINER_GPUS</code> when using the <code>Trainer</code> module. A <a href="https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae">patch</a> is included in the <code>1.6.0</code> release.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2022-0845">https://nvd.nist.gov/vuln/detail/CVE-2022-0845</a></li>
<li><a href="https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae">https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae</a></li>
<li><a href="https://huntr.dev/bounties/a795bf93-c91e-4c79-aae8-f7d8bda92e2a">https://huntr.dev/bounties/a795bf93-c91e-4c79-aae8-f7d8bda92e2a</a></li>
<li><a href="https://github.com/PyTorchLightning/pytorch-lightning/pull/12212">https://github.com/PyTorchLightning/pytorch-lightning/pull/12212</a></li>
<li><a href="https://github.com/advisories/GHSA-r5qj-cvf9-p85h">https://github.com/advisories/GHSA-r5qj-cvf9-p85h</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/pytorch-lightning/PYSEC-2022-181.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/pytorch-lightning/PYSEC-2022-181.yaml</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-r5qj-cvf9-p85h</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2022-03-06T00:00:16.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[python-libnmap] Argument injection in python-libnmap]]></title>
        <id>https://github.com/advisories/GHSA-qwqv-j7jr-4hp6</id>
        <link href="https://github.com/advisories/GHSA-qwqv-j7jr-4hp6"/>
        <updated>2024-10-25T20:49:08.000Z</updated>
        <content type="html"><![CDATA[<p>In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments).</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2022-30284">https://nvd.nist.gov/vuln/detail/CVE-2022-30284</a></li>
<li><a href="https://github.com/savon-noir/python-libnmap/releases">https://github.com/savon-noir/python-libnmap/releases</a></li>
<li><a href="https://libnmap.readthedocs.io/en/latest/process.html#using-libnmap-process">https://libnmap.readthedocs.io/en/latest/process.html#using-libnmap-process</a></li>
<li><a href="https://github.com/savon-noir/python-libnmap/commit/c36fecde90017befeb4853396d0e2aac93c95b64">https://github.com/savon-noir/python-libnmap/commit/c36fecde90017befeb4853396d0e2aac93c95b64</a></li>
<li><a href="https://github.com/savon-noir/python-libnmap/releases/tag/v0.7.3">https://github.com/savon-noir/python-libnmap/releases/tag/v0.7.3</a></li>
<li><a href="https://pypi.org/project/python-libnmap">https://pypi.org/project/python-libnmap</a></li>
<li><a href="https://www.swascan.com/security-advisory-libnmap-2">https://www.swascan.com/security-advisory-libnmap-2</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/python-libnmap/PYSEC-2022-42999.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/python-libnmap/PYSEC-2022-42999.yaml</a></li>
<li><a href="https://github.com/advisories/GHSA-qwqv-j7jr-4hp6">https://github.com/advisories/GHSA-qwqv-j7jr-4hp6</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-qwqv-j7jr-4hp6</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2022-05-06T00:00:54.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[quart] Werkzeug possible resource exhaustion when parsing file data in forms]]></title>
        <id>https://github.com/advisories/GHSA-q34m-jh98-gwm2</id>
        <link href="https://github.com/advisories/GHSA-q34m-jh98-gwm2"/>
        <updated>2024-10-25T21:35:41.000Z</updated>
        <content type="html"><![CDATA[<p>Applications using Werkzeug to parse <code>multipart/form-data</code> requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the <code>Request.max_form_memory_size</code> setting.</p>
<p>The <code>Request.max_content_length</code> setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2">https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2</a></li>
<li><a href="https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee">https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee</a></li>
<li><a href="https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b">https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b</a></li>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2024-49767">https://nvd.nist.gov/vuln/detail/CVE-2024-49767</a></li>
<li><a href="https://github.com/pallets/werkzeug/releases/tag/3.0.6">https://github.com/pallets/werkzeug/releases/tag/3.0.6</a></li>
<li><a href="https://github.com/advisories/GHSA-q34m-jh98-gwm2">https://github.com/advisories/GHSA-q34m-jh98-gwm2</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-q34m-jh98-gwm2</uri>
        </author>
        <category label="severity" term="MODERATE"/>
        <published>2024-10-25T19:44:43.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[werkzeug] Werkzeug possible resource exhaustion when parsing file data in forms]]></title>
        <id>https://github.com/advisories/GHSA-q34m-jh98-gwm2</id>
        <link href="https://github.com/advisories/GHSA-q34m-jh98-gwm2"/>
        <updated>2024-10-25T21:35:41.000Z</updated>
        <content type="html"><![CDATA[<p>Applications using Werkzeug to parse <code>multipart/form-data</code> requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the <code>Request.max_form_memory_size</code> setting.</p>
<p>The <code>Request.max_content_length</code> setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2">https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2</a></li>
<li><a href="https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee">https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee</a></li>
<li><a href="https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b">https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b</a></li>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2024-49767">https://nvd.nist.gov/vuln/detail/CVE-2024-49767</a></li>
<li><a href="https://github.com/pallets/werkzeug/releases/tag/3.0.6">https://github.com/pallets/werkzeug/releases/tag/3.0.6</a></li>
<li><a href="https://github.com/advisories/GHSA-q34m-jh98-gwm2">https://github.com/advisories/GHSA-q34m-jh98-gwm2</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-q34m-jh98-gwm2</uri>
        </author>
        <category label="severity" term="MODERATE"/>
        <published>2024-10-25T19:44:43.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[Werkzeug] Werkzeug safe_join not safe on Windows]]></title>
        <id>https://github.com/advisories/GHSA-f9vj-2wh5-fj8j</id>
        <link href="https://github.com/advisories/GHSA-f9vj-2wh5-fj8j"/>
        <updated>2024-10-26T03:47:04.000Z</updated>
        <content type="html"><![CDATA[<p>On Python &lt; 3.11 on Windows, <code>os.path.isabs()</code> does not catch UNC paths like <code>//server/share</code>. Werkzeug's <code>safe_join()</code> relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python &gt;= 3.11, or not using Windows, are not vulnerable.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j">https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j</a></li>
<li><a href="https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092">https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092</a></li>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2024-49766">https://nvd.nist.gov/vuln/detail/CVE-2024-49766</a></li>
<li><a href="https://github.com/pallets/werkzeug/releases/tag/3.0.6">https://github.com/pallets/werkzeug/releases/tag/3.0.6</a></li>
<li><a href="https://github.com/advisories/GHSA-f9vj-2wh5-fj8j">https://github.com/advisories/GHSA-f9vj-2wh5-fj8j</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-f9vj-2wh5-fj8j</uri>
        </author>
        <category label="severity" term="MODERATE"/>
        <published>2024-10-25T19:43:41.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[aim] Aim Web API vulnerable to Remote Code Execution]]></title>
        <id>https://github.com/advisories/GHSA-mxvw-cj37-8g2h</id>
        <link href="https://github.com/advisories/GHSA-mxvw-cj37-8g2h"/>
        <updated>2024-10-25T19:18:59.000Z</updated>
        <content type="html"><![CDATA[<p>A critical Remote Code Execution (RCE) vulnerability was identified in the aimhubio/aim project, specifically within the <code>/api/runs/search/run/</code> endpoint, affecting versions &gt;= 3.0.0. The vulnerability resides in the <code>run_search_api</code> function of the <code>aim/web/api/runs/views.py</code> file, where improper restriction of user access to the <code>RunView</code> object allows for the execution of arbitrary code via the <code>query</code> parameter. This issue enables attackers to execute arbitrary commands on the server, potentially leading to full system compromise.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2024-2195">https://nvd.nist.gov/vuln/detail/CVE-2024-2195</a></li>
<li><a href="https://huntr.com/bounties/22f2355e-b875-4c01-b454-327e5951c018">https://huntr.com/bounties/22f2355e-b875-4c01-b454-327e5951c018</a></li>
<li><a href="https://github.com/advisories/GHSA-mxvw-cj37-8g2h">https://github.com/advisories/GHSA-mxvw-cj37-8g2h</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-mxvw-cj37-8g2h</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2024-04-10T18:30:48.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[starkbank-ecdsa] Improper Verification of Cryptographic Signature in starkbank-ecdsa]]></title>
        <id>https://github.com/advisories/GHSA-92vm-mxjf-jqf3</id>
        <link href="https://github.com/advisories/GHSA-92vm-mxjf-jqf3"/>
        <updated>2024-10-25T14:49:42.000Z</updated>
        <content type="html"><![CDATA[<p>The <code>verify</code> function in the Stark Bank Python ECDSA library (starkbank-ecdsa) 2.0.0 fails to check that the signature is non-zero, which allows attackers to forge signatures on arbitrary messages.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2021-43572">https://nvd.nist.gov/vuln/detail/CVE-2021-43572</a></li>
<li><a href="https://github.com/starkbank/ecdsa-python/releases/tag/v2.0.1">https://github.com/starkbank/ecdsa-python/releases/tag/v2.0.1</a></li>
<li><a href="https://github.com/starkbank/ecdsa-python/commit/d136170666e9510eb63c2572551805807bd4c17f">https://github.com/starkbank/ecdsa-python/commit/d136170666e9510eb63c2572551805807bd4c17f</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/starkbank-ecdsa/PYSEC-2021-426.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/starkbank-ecdsa/PYSEC-2021-426.yaml</a></li>
<li><a href="https://research.nccgroup.com/2021/11/08/technical-advisory-arbitrary-signature-forgery-in-stark-bank-ecdsa-libraries">https://research.nccgroup.com/2021/11/08/technical-advisory-arbitrary-signature-forgery-in-stark-bank-ecdsa-libraries</a></li>
<li><a href="https://github.com/advisories/GHSA-92vm-mxjf-jqf3">https://github.com/advisories/GHSA-92vm-mxjf-jqf3</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-92vm-mxjf-jqf3</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2021-11-10T20:41:39.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[snowflake-connector-python] The Snowflake Connector for Python stores sensitive data in logs]]></title>
        <id>https://github.com/advisories/GHSA-5vvg-pvhp-hv2m</id>
        <link href="https://github.com/advisories/GHSA-5vvg-pvhp-hv2m"/>
        <updated>2024-10-25T16:47:18.000Z</updated>
        <content type="html"><![CDATA[<h3 id="issue">Issue</h3>
<p>Snowflake recently learned about and remediated a set of vulnerabilities in the Snowflake Connector for Python. Under specific conditions, certain users credentials (or portions of those credentials) were logged locally by the Connector to the users own systems. The credentials were not logged by Snowflake.</p>
<p>These vulnerabilities affect versions up to and including 3.12.2. Snowflake fixed the issue in version 3.12.3.</p>
<h3 id="vulnerability-details">Vulnerability Details</h3>
<p>When the logging level was set by the user to DEBUG, the Connector could have logged Duo passcodes (when specified via the “passcode” parameter) and Azure SAS tokens. Additionally, the <a href="https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-example#logging">SecretDetector</a> logging formatter, if enabled, contained bugs which caused it to not fully redact JWT tokens and certain private key formats.</p>
<h3 id="solution">Solution</h3>
<p>Snowflake released version 3.12.3 of the Snowflake Connector for Python, which fixes these issues. We recommend users upgrade to version 3.12.3 and review their logs for any potentially sensitive information that may have been captured.</p>
<h3 id="additional-information">Additional Information</h3>
<p>If you discover a security vulnerability in one of our products or websites, please report the issue to HackerOne. For more information, please see our <a href="https://hackerone.com/snowflake?type=team">Vulnerability Disclosure Policy</a>.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://github.com/snowflakedb/snowflake-connector-python/security/advisories/GHSA-5vvg-pvhp-hv2m">https://github.com/snowflakedb/snowflake-connector-python/security/advisories/GHSA-5vvg-pvhp-hv2m</a></li>
<li><a href="https://github.com/snowflakedb/snowflake-connector-python/commit/dbc9284a3c0382c131b971b35e8d6ab93c46f37a">https://github.com/snowflakedb/snowflake-connector-python/commit/dbc9284a3c0382c131b971b35e8d6ab93c46f37a</a></li>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2024-49750">https://nvd.nist.gov/vuln/detail/CVE-2024-49750</a></li>
<li><a href="https://github.com/advisories/GHSA-5vvg-pvhp-hv2m">https://github.com/advisories/GHSA-5vvg-pvhp-hv2m</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-5vvg-pvhp-hv2m</uri>
        </author>
        <category label="severity" term="MODERATE"/>
        <published>2024-10-24T22:42:26.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[python-keystoneclient] Insufficient Verification of Data Authenticity in python-keystoneclient]]></title>
        <id>https://github.com/advisories/GHSA-9vg3-cf92-h2h7</id>
        <link href="https://github.com/advisories/GHSA-9vg3-cf92-h2h7"/>
        <updated>2024-10-24T21:58:16.000Z</updated>
        <content type="html"><![CDATA[<p>python-keystoneclient version 0.2.3 to 0.2.5 has middleware memcache signing bypass</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2013-2167">https://nvd.nist.gov/vuln/detail/CVE-2013-2167</a></li>
<li><a href="https://github.com/openstack/python-keystoneclient/commit/eeefb784f24c37d5f56a421e1ccc911cace9385e">https://github.com/openstack/python-keystoneclient/commit/eeefb784f24c37d5f56a421e1ccc911cace9385e</a></li>
<li><a href="https://access.redhat.com/security/cve/cve-2013-2167">https://access.redhat.com/security/cve/cve-2013-2167</a></li>
<li><a href="https://bugs.gentoo.org/show_bug.cgi?id=CVE-2013-2167">https://bugs.gentoo.org/show_bug.cgi?id=CVE-2013-2167</a></li>
<li><a href="https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2167">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2167</a></li>
<li><a href="https://exchange.xforce.ibmcloud.com/vulnerabilities/85492">https://exchange.xforce.ibmcloud.com/vulnerabilities/85492</a></li>
<li><a href="https://github.com/openstack/python-keystoneclient/commits/0.3.0">https://github.com/openstack/python-keystoneclient/commits/0.3.0</a></li>
<li><a href="https://security-tracker.debian.org/tracker/CVE-2013-2167">https://security-tracker.debian.org/tracker/CVE-2013-2167</a></li>
<li><a href="http://lists.fedoraproject.org/pipermail/package-announce/2013-August/113944.html">http://lists.fedoraproject.org/pipermail/package-announce/2013-August/113944.html</a></li>
<li><a href="http://rhn.redhat.com/errata/RHSA-2013-0992.html">http://rhn.redhat.com/errata/RHSA-2013-0992.html</a></li>
<li><a href="http://www.openwall.com/lists/oss-security/2013/06/19/5">http://www.openwall.com/lists/oss-security/2013/06/19/5</a></li>
<li><a href="https://github.com/advisories/GHSA-9vg3-cf92-h2h7">https://github.com/advisories/GHSA-9vg3-cf92-h2h7</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/python-keystoneclient/PYSEC-2019-161.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/python-keystoneclient/PYSEC-2019-161.yaml</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-9vg3-cf92-h2h7</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2020-03-10T20:39:05.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[pywps] XML External Entity Injection in PyWPS]]></title>
        <id>https://github.com/advisories/GHSA-p9wf-3xpg-c9g5</id>
        <link href="https://github.com/advisories/GHSA-p9wf-3xpg-c9g5"/>
        <updated>2024-10-24T21:53:22.000Z</updated>
        <content type="html"><![CDATA[<p>An XML external entity (XXE) injection in PyWPS before 4.5.0 allows an attacker to view files on the application server filesystem by assigning a path to the entity. OWSLib 0.24.1 may also be affected.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2021-39371">https://nvd.nist.gov/vuln/detail/CVE-2021-39371</a></li>
<li><a href="https://github.com/geopython/OWSLib/issues/790">https://github.com/geopython/OWSLib/issues/790</a></li>
<li><a href="https://github.com/geopython/pywps/pull/616">https://github.com/geopython/pywps/pull/616</a></li>
<li><a href="https://lists.debian.org/debian-lts-announce/2021/09/msg00001.html">https://lists.debian.org/debian-lts-announce/2021/09/msg00001.html</a></li>
<li><a href="https://github.com/geopython/pywps/commit/7d6b26a2e931df2feca0b7fb24f4d01610825aee">https://github.com/geopython/pywps/commit/7d6b26a2e931df2feca0b7fb24f4d01610825aee</a></li>
<li><a href="https://github.com/advisories/GHSA-p9wf-3xpg-c9g5">https://github.com/advisories/GHSA-p9wf-3xpg-c9g5</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/pywps/PYSEC-2021-121.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/pywps/PYSEC-2021-121.yaml</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-p9wf-3xpg-c9g5</uri>
        </author>
        <category label="severity" term="HIGH"/>
        <published>2021-09-02T17:11:13.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[pysaml2] PySAML2 XML external entity attack]]></title>
        <id>https://github.com/advisories/GHSA-m269-wj6g-c459</id>
        <link href="https://github.com/advisories/GHSA-m269-wj6g-c459"/>
        <updated>2024-10-24T21:52:38.000Z</updated>
        <content type="html"><![CDATA[<p>PySAML2 allows remote attackers to conduct XML external entity (XXE) attacks via a crafted SAML XML request or response.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2016-10127">https://nvd.nist.gov/vuln/detail/CVE-2016-10127</a></li>
<li><a href="https://github.com/rohe/pysaml2/issues/366">https://github.com/rohe/pysaml2/issues/366</a></li>
<li><a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a></li>
<li><a href="https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b">https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b</a></li>
<li><a href="https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716">https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716</a></li>
<li><a href="http://www.openwall.com/lists/oss-security/2017/01/19/5">http://www.openwall.com/lists/oss-security/2017/01/19/5</a></li>
<li><a href="https://github.com/advisories/GHSA-m269-wj6g-c459">https://github.com/advisories/GHSA-m269-wj6g-c459</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/pysaml2/PYSEC-2017-67.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/pysaml2/PYSEC-2017-67.yaml</a></li>
<li><a href="https://web.archive.org/web/20200227195127/http://www.securityfocus.com/bid/95376">https://web.archive.org/web/20200227195127/http://www.securityfocus.com/bid/95376</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-m269-wj6g-c459</uri>
        </author>
        <category label="severity" term="CRITICAL"/>
        <published>2022-05-17T02:56:23.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[Pygments] Pygments vulnerable to ReDoS]]></title>
        <id>https://github.com/advisories/GHSA-mrwq-x4v8-fh7p</id>
        <link href="https://github.com/advisories/GHSA-mrwq-x4v8-fh7p"/>
        <updated>2024-10-24T21:49:47.000Z</updated>
        <content type="html"><![CDATA[<p>A ReDoS issue was discovered in <code>pygments/lexers/smithy.py</code> in Pygments until 2.15.0 via SmithyLexer.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2022-40896">https://nvd.nist.gov/vuln/detail/CVE-2022-40896</a></li>
<li><a href="https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61">https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61</a></li>
<li><a href="https://github.com/pygments/pygments/commit/97eb3d5ec7c1b3ea4fcf9dee30a2309cf92bd194">https://github.com/pygments/pygments/commit/97eb3d5ec7c1b3ea4fcf9dee30a2309cf92bd194</a></li>
<li><a href="https://github.com/pygments/pygments/commit/dd52102c38ebe78cd57748e09f38929fd283ad04">https://github.com/pygments/pygments/commit/dd52102c38ebe78cd57748e09f38929fd283ad04</a></li>
<li><a href="https://github.com/pygments/pygments/commit/fdf182a7af85b1deeeb637ca970d31935e7c9d52">https://github.com/pygments/pygments/commit/fdf182a7af85b1deeeb637ca970d31935e7c9d52</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/pygments/PYSEC-2023-117.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/pygments/PYSEC-2023-117.yaml</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EZGMXALE3HSP4OXC7UUWIKX3OXKZDTY3">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EZGMXALE3HSP4OXC7UUWIKX3OXKZDTY3</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VUZO4BQCIY2S2KZYHERQMKURB7AHXDBO">https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VUZO4BQCIY2S2KZYHERQMKURB7AHXDBO</a></li>
<li><a href="https://pypi.org/project/Pygments">https://pypi.org/project/Pygments</a></li>
<li><a href="https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2">https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2</a></li>
<li><a href="https://github.com/advisories/GHSA-mrwq-x4v8-fh7p">https://github.com/advisories/GHSA-mrwq-x4v8-fh7p</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-mrwq-x4v8-fh7p</uri>
        </author>
        <category label="severity" term="MODERATE"/>
        <published>2023-07-19T15:30:26.000Z</published>
    </entry>
    <entry>
        <title type="html"><![CDATA[[pyspark] Sensitive data written to disk unencrypted in Spark]]></title>
        <id>https://github.com/advisories/GHSA-fp5j-3fpf-mhj5</id>
        <link href="https://github.com/advisories/GHSA-fp5j-3fpf-mhj5"/>
        <updated>2024-10-24T21:48:37.000Z</updated>
        <content type="html"><![CDATA[<p>Prior to Spark 2.3.3, in certain situations Spark would write user data to local disk unencrypted, even if spark.io.encryption.enabled=true. This includes cached blocks that are fetched to disk (controlled by spark.maxRemoteBlockSizeFetchToMem); in SparkR, using parallelize; in Pyspark, using broadcast and parallelize; and use of python udfs.</p>
<h3 id="references">References</h3>
<ul>
<li><a href="https://nvd.nist.gov/vuln/detail/CVE-2019-10099">https://nvd.nist.gov/vuln/detail/CVE-2019-10099</a></li>
<li><a href="https://lists.apache.org/thread.html/c2a39c207421797f82823a8aff488dcd332d9544038307bf69a2ba9e@%3Cuser.spark.apache.org%3E">https://lists.apache.org/thread.html/c2a39c207421797f82823a8aff488dcd332d9544038307bf69a2ba9e@%3Cuser.spark.apache.org%3E</a></li>
<li><a href="https://lists.apache.org/thread.html/rabe1d47e2bf8b8f6d9f3068c8d2679731d57fa73b3a7ed1fa82406d2@%3Cissues.spark.apache.org%3E">https://lists.apache.org/thread.html/rabe1d47e2bf8b8f6d9f3068c8d2679731d57fa73b3a7ed1fa82406d2@%3Cissues.spark.apache.org%3E</a></li>
<li><a href="https://lists.apache.org/thread.html/ra216b7b0dd82a2c12c2df9d6095e689eb3f3d28164e6b6587da69fae@%3Ccommits.spark.apache.org%3E">https://lists.apache.org/thread.html/ra216b7b0dd82a2c12c2df9d6095e689eb3f3d28164e6b6587da69fae@%3Ccommits.spark.apache.org%3E</a></li>
<li><a href="https://github.com/pypa/advisory-database/tree/main/vulns/pyspark/PYSEC-2019-114.yaml">https://github.com/pypa/advisory-database/tree/main/vulns/pyspark/PYSEC-2019-114.yaml</a></li>
<li><a href="https://github.com/advisories/GHSA-fp5j-3fpf-mhj5">https://github.com/advisories/GHSA-fp5j-3fpf-mhj5</a></li>
</ul>
]]></content>
        <author>
            <name>GitHub</name>
            <email>GitHub@noreply.github.com</email>
            <uri>https://github.com/advisories/GHSA-fp5j-3fpf-mhj5</uri>
        </author>
        <category label="severity" term="HIGH"/>
        <published>2019-08-08T15:18:22.000Z</published>
    </entry>
</feed>